== Homework 4 - Due Friday Sept 11, 5pm

_The semi-empirical mass formula_

In nuclear physics, the semi-empirical mass formula is a formula for
calculating the approximate nuclear binding energy latexmath:[$B$] of an
atomic nucleus with atomic number latexmath:[$Z$] and mass number
latexmath:[$A$]. The formula looks like this:

[latexmath]
++++
\[ B = a_1 A - a_2 A^{2/3} - a_3 \frac{Z^2}{A^{1/3}} - a_4 \frac{(A - 2Z)^2}{A} - \frac{a_5}{A^{1/2}} \]
++++

where, in units of millions of electron volts (MeV), the constants are
latexmath:[$a_1 = 15.67$], latexmath:[$a_2 = 17.23$],
latexmath:[$a_3 = 0.75$], latexmath:[$a_4 = 93.2$], and

[latexmath]
++++
\[ a_5  \; =  \;\; \left\{ \begin{array} {r@{\quad\tt if \quad}l} 0 & A \;{\tt is
      \; odd}, \\
    12.0 & A \;{\tt and}\; Z \;{\tt are \;both \;even}, \\ -12.0 & A \;{\tt is
     \;  even \; and}\;  Z \;{\tt is
  \;  odd.} \end{array} \right. \]
++++

Write a function that takes as its input the values of latexmath:[$A$]
and latexmath:[$Z$], and prints out: * (a) the binding energy
latexmath:[$B$] for the corresponding atom and * (b) the binding energy
per nucleon, which is latexmath:[$B/A$].

Use your program to find the binding energy of an atom with
latexmath:[$A = 58$] and latexmath:[$Z = 28$]. (Hint: The correct answer
is around 490 MeV.)

Also run, latexmath:[$A = 59$] and latexmath:[$Z = 28$] and
latexmath:[$A = 58$] and latexmath:[$Z = 27$].


+*In[8]:*+
[source, ipython3]
----
a1 = 15.67
a2 = 17.23
a3 = 0.75
a4 = 93.2
a5 = int(input("A: "))
if A / 2 != int:
    a5 == 0
if A / 2 == int and Z / 2 == int:
    a5 == 12
if A / 2 == int and Z / 2 != int:
    a5 == (-12)
Z = int(input("Z: "))    

def formula(B):
    return B == a1*A - a2*(A**(2/3)) - a3*((Z**2)/A**(1/3)) - a4*(((A-2*Z)**2)/A) - (a5/A**(1/2))

print(formula(B)) 

----


+*Out[8]:*+
----
A: 2


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    <ipython-input-8-03d21cf75908> in <module>
          4 a4 = 93.2
          5 a5 = int(input("A: "))
    ----> 6 if A / 2 != int:
          7     a5 == 0
          8 if A / 2 == int and Z / 2 == int:


    NameError: name 'A' is not defined

----


